### ISSUE TITLE
Questions about reformatting

### ISSUE THREAD

**Issue by FrankVerhoef** [ReScience/RC-2020#4]
Hi , I just finished a first round of reformatting.
Some questions:
- As the margins in the RC-2020 are much wider, all of the tables in the document had to be reformatted, some of them split into two parts. This takes (much) more space --> I hope this will not be a problem.
- We used bold, italic and some colors in our text (e.g. to highlight notable differences in tables). But in the RC-2020 format the codes don't work (e.g. \textit, \textbf) --> how can I include these.
- If you have suggestions about the other warnings in the build.log, please let me know!
Thank you, Frank

[build.log](https://github.com/ReScience/RC-2020/files/6290908/build.log)

**Comment by koustuvsinha** [comment]
- Yes, no issues with camera ready taking more space due to table expansions!
- From your build.log, I find the first error to be this:

  ```
  ! LaTeX Error: Option clash for package xcolor.
  ```
  Firstly, please remove the import of `xcolor`. The `xcolor` package is already loaded by rescience.cls, which is why it is creating problems for submissions. I checked your package.tex, and it seems the offending color is `OliveGreen`. If I change it to green, then the compilation proceeds : `\newcommand{\green}[1]{\textbf{\textcolor{green}{#1}}}`.
 
- Regarding the bold and italics, I narrowed down the issue to import of `fontenc`. Since ReScience uses custom fonts, loading this package will overwrite the custom fonts and will break textbf / texit. Please remove / comment this line from your package.tex : `\usepackage[T1]{fontenc}    % use 8-bit T1 fonts`. Thanks for bringing this to my attention though! I'll add a note in the readme!
